it_help_service/helpdesk/urls.py
from django.urls import path

from . import views
# добавим пространство имен
app_name = 'helpdesk'
urlpatterns = [
    # /helpdesk/
    path('', views.index, name='index'),
    # /helpdesk/orders
    path('orders/', views.orders, name='orders'),
    # /helpdesk/orders/order/1
    path('orders/order/<int:order_id>/', views.detail, name='detail'),
]

it_help_service/it_help_service/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helpdesk/', include('helpdesk.urls')),
]

it_help_service/helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import mimetypes
from .validators import validate_file_extension


class Orders(models.Model):
    """Класс для описания заявки"""

    class Meta:
        db_table = 'orders'
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    statuses = (('new', 'Новая'),
                ('read', 'Прочитана'))

    author = models.ForeignKey(User, on_delete=models.RESTRICT, verbose_name="Автор")
    theme = models.CharField(verbose_name="Тема", max_length=250)
    content = models.TextField(verbose_name="Текст", null=True)
    create_date = models.DateTimeField(verbose_name="Создано", auto_now_add=True)
    edit_date = models.DateTimeField(verbose_name="Изменено", blank=True, null=True)
    status = models.CharField(verbose_name='Статус', max_length=25, choices=statuses, null=True)

    def __str__(self):
        return f'Заявка №{self.id} на тему "{self.theme}" от {self.author.username}'

    def save(self, *args, **kwargs):
        self.edit_date = datetime.now()
        super().save(self, *args, **kwargs)


def attachment_path(instance, filename):
    return instance.attachment_path(filename)


class Attachment(models.Model):
    """
    Представляет файл, прикрепленный к последующему действию.
    Это может быть вложение в электронном письме или загрузка через веб-интерфейс.
    """

    class Meta:
        verbose_name = 'Вложение'
        verbose_name_plural = 'Вложения'
        db_table = 'attachments'

    order = models.ForeignKey(
        Orders,
        on_delete=models.CASCADE,
        verbose_name='Обращение'
    )

    file = models.BinaryField()

    filename = models.CharField(
        blank=True,
        max_length=1000,
        validators=[validate_file_extension]
    )

    mime_type = models.CharField(
        blank=True,
        max_length=255,
    )

    size = models.IntegerField(
        blank=True,
        help_text='Размер файла в байтах',
    )

    def __str__(self):
        return '%s' % self.filename

    def save(self, *args, **kwargs):

        if not self.size:
            self.size = self.get_size()

        if not self.filename:
            self.filename = self.get_filename()

        if not self.mime_type:
            self.mime_type = \
                mimetypes.guess_type(self.filename, strict=False)[0] or \
                'application/octet-stream'

        return super.save(*args, **kwargs)

    def get_filename(self):
        return str(self.file)

    def get_size(self):
        return self.file.file.size

it_help_service/helpdesk/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Orders


def index(request):
    # todo должна быть логика для новых отображения обращений (Админ видит все обращения, а обычный пользователь только свои)
    # todo добавить стилей в шаблон index.html
    orders = Orders.objects.filter(status='new').order_by('create_date')
    context = {
        'orders': orders
    }
    return render(request, 'helpdesk/index.html', context)


def detail(request, order_id):
    # todo добавить стилей в шаблон order.html
    order = get_object_or_404(Orders, pk=order_id)
    return render(request, 'helpdesk/order.html', {'order': order})


def orders(request):
    # todo добавить стилей в шаблон orders.html
    orders = Orders.objects.all()
    return render(request, 'helpdesk/orders.html', {'orders': orders})

it_help_service/helpdesk/templates/helpdesk/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HELPDESK</title>
</head>
<body>
{% if orders %}
    <ul>
    {% for order in orders %}
        <li><a href="{% url 'helpdesk:detail' order.id %}">{{ order }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет новых обращений</p>
{% endif %}
</body>
</html>

it_help_service/helpdesk/templates/helpdesk/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказ №{{order.id}}</title>
</head>
<body>
<h1>Заказ №{{order.id}} от {{order.create_date}}</h1>
<hr>
    <p>Тема: {{order.theme}}</p>
    <p>Текст: {{order.content}}</p>
    <p>Статус: {{order.status}}</p>
    <p>Автор: {{order.author.username}}</p>
    <p>Дата изменения: {{order.edit_date}}</p>
</body>
</html>

it_help_service/helpdesk/templates/helpdesk/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказы</title>
</head>
<body>
{% if orders %}
    <ul>
    {% for order in orders %}
        <li><a href="{% url 'helpdesk:detail' order.id %}">{{ order }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Обращения не найдены</p>
{% endif %}
</body>
</html>